Update ota

diff --git a/luci-app-ota/root/bin/ota b/luci-app-ota/root/bin/ota
--- a/luci-app-ota/root/bin/ota
+++ b/luci-app-ota/root/bin/ota
@@ -18,34 +18,34 @@ sha256() {
 
 download() {
     read_json
-    if [ -f /tmp/firmware.img ]; then
-        echo "Checking existed firmware.img..." >> /tmp/firmware.img.progress
-        if [ "`sha256 /tmp/firmware.img`" = "$FW_SHA256SUM" ]; then
+    if [ -f /tmp/firmware.itb ]; then
+        echo "Checking existed firmware.itb..." >> /tmp/firmware.itb.progress
+        if [ "`sha256 /tmp/firmware.itb`" = "$FW_SHA256SUM" ]; then
             return 0;
         else
-            echo "Check failed, redownload" >> /tmp/firmware.img.progress
-            rm -f /tmp/firmware.img
+            echo "Check failed, redownload" >> /tmp/firmware.itb.progress
+            rm -f /tmp/firmware.itb
         fi
     fi
-    touch /tmp/firmware.img.progress
-    fw_download_tool "$FW_URL" -o /tmp/firmware.img.part -k -L -4 > /tmp/firmware.img.progress 2>&1 &
+    touch /tmp/firmware.itb.progress
+    fw_download_tool "$FW_URL" -o /tmp/firmware.itb.part -k -L -4 > /tmp/firmware.itb.progress 2>&1 &
     echo "$! $PPID" > /var/run/ota/download.pid
     while true; do
-        progress=$(grep -c "100.00%" /tmp/firmware.img.progress)
+        progress=$(grep -c "100.00%" /tmp/firmware.itb.progress)
         if [ "$progress" -ge "1" ]; then
-            echo "Checking new firmware.img.part..." > /tmp/firmware.img.progress
+            echo "Checking new firmware.itb.part..." > /tmp/firmware.itb.progress
             break
         fi
         sleep 1
     done
-    if [ "`sha256 /tmp/firmware.img.part`" = "$FW_SHA256SUM" ]; then
-        mv /tmp/firmware.img.part /tmp/firmware.img && echo $FW_SHA256SUM > /tmp/firmware.img.sha256sum
-        rm -f /tmp/firmware.img.progress
+    if [ "`sha256 /tmp/firmware.itb.part`" = "$FW_SHA256SUM" ]; then
+        mv /tmp/firmware.itb.part /tmp/firmware.itb && echo $FW_SHA256SUM > /tmp/firmware.itb.sha256sum
+        rm -f /tmp/firmware.itb.progress
         return 0
     else
-        echo "Checksum failed!" >>/tmp/firmware.img.progress
+        echo "Checksum failed!" >>/tmp/firmware.itb.progress
         sleep 1
-        rm -rf /tmp/firmware.img.part
+        rm -rf /tmp/firmware.itb.part
         return 1
     fi
 }
@@ -86,12 +86,12 @@ do_download(){
 # 0: done, 1: downloading, 2: failed, *: err
 do_progress() {
     read_json
-    [ -f /tmp/firmware.img.sha256sum ] && [ "`cat /tmp/firmware.img.sha256sum`" = "$FW_SHA256SUM" ] && return 0
-    [ -f /tmp/firmware.img.progress ] || { echo "download not in progress" >&2 ; return 254; }
-    [ -f /tmp/firmware.img.part ] && { cat /tmp/firmware.img.progress | tr '\r' '\n' | tail -n1; return 1; }
-    tail -1 /tmp/firmware.img.progress | grep -Fq 'Canceled!' && { echo "Canceled"; return 2; }
-    tail -1 /tmp/firmware.img.progress | grep -Fq 'Checksum failed!' && { echo "Checksum failed!"; return 254; }
-    grep -v '\r' /tmp/firmware.img.progress >&2
+    [ -f /tmp/firmware.itb.sha256sum ] && [ "`cat /tmp/firmware.itb.sha256sum`" = "$FW_SHA256SUM" ] && return 0
+    [ -f /tmp/firmware.itb.progress ] || { echo "download not in progress" >&2 ; return 254; }
+    [ -f /tmp/firmware.itb.part ] && { cat /tmp/firmware.itb.progress | tr '\r' '\n' | tail -n1; return 1; }
+    tail -1 /tmp/firmware.itb.progress | grep -Fq 'Canceled!' && { echo "Canceled"; return 2; }
+    tail -1 /tmp/firmware.itb.progress | grep -Fq 'Checksum failed!' && { echo "Checksum failed!"; return 254; }
+    grep -v '\r' /tmp/firmware.itb.progress >&2
     return 1
 }
 
@@ -105,9 +105,9 @@ do_cancel() {
                     break
                 fi
             done
-            rm -rf /tmp/firmware.img* /var/lock/ota_background.lock /var/lock/ota_api.lock /var/run/ota/download.pid
-            echo "" >> /tmp/firmware.img.progress
-            echo "Canceled!" >> /tmp/firmware.img.progress
+            rm -rf /tmp/firmware.itb* /var/lock/ota_background.lock /var/lock/ota_api.lock /var/run/ota/download.pid
+            echo "" >> /tmp/firmware.itb.progress
+            echo "Canceled!" >> /tmp/firmware.itb.progress
         fi
     fi
     return 0
